# Book settings
title: The Practical Testing Book
author: The World
logo: logo.png

# Information about where the book exists on the web
repository:
  url: https://github.com/damorimRG/practical_testing_book
launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

latex:
  latex_documents:
    targetname: book.tex
    
exclude_patterns: [pattern1/*, fundamentals/README.md]
#exclude_patterns: [pattern1/*, fundamentals/README.md,testgranularity/acceptancetesting.md]

execute:
  execute_notebooks: 'off'